server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "my-awesome-app"
  mail:
    host: smtp.gmail.com
    port: 587
    username: karncs88
    password: tptdlfktqppgensv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
      name: email
---
app:
  email:
    from: karncomsci26@gmail.com
